### ISSUE TITLE
Caused by: org.apache.catalina.connector.ClientAbortException: java.io.EOFException: Unexpected EOF read on the socket

### ISSUE THREAD

**Issue by CainChao** [univapay/univapay-java-sdk#197]
Receive your webhook callbacks, and obtain your request parameters through ServletInputStream parsing. Report Caused by: org.apache.catalina.connector.ClientAbortException: java.io.EOFException: Unexpected EOF read on the socket

**Comment by andrezimmermann** [comment]
Hello, thank you for reaching out. 
This is unrelated with the java sdk so I will close this, hope you understand.

As for the issue it, it seems that the webhook 3 seconds limit was reached. Like the exception said, there was a unexpected "end of file" when you were reading the webhook's request.

For debugging purposes, I suggest to create another webhook, targeting the "bin" generated by https://mockbin.org/
That way you can check the event that would be generated.

Seems you're using Tomcat as the web server, I'd suggest the following code for reading the request body..

```
public String readRequestBody(InputStream inputStream) throws IOException {
    byte[] content = null
    
     final byte[] content ;
     try (inputStream) {
         bytes = inputStream.readAllBytes();
     } catch (Exception error) {
        throw new IOException("Something went wrong", error)
     }
     
      //I'm hard coding UTF8, I think that would be fine, but ideally would read from the request headers
     return new String(content, Charset.UTF8);

}
```

Ideally you read the data, persist the event, return OK under the 3 seconds limit. Then in async fashion, you process the event received. 

If you confirm that indeed that you aren't receiving any data at https://mockbin.org/ and still having issues, please feel free to reach out again 😃
